//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreChain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consignment
    {
        public int ID { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public int Volume { get; set; }
    
        public virtual Provider Provider { get; set; }
        public virtual STORE STORE { get; set; }
    }
}
