//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreChain.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChainOfStoresEntities : DbContext
    {
        public ChainOfStoresEntities()
            : base("name=ChainOfStoresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Consignment> Consignment { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<STORE> STORE { get; set; }
    }
}
