//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreChain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STORE()
        {
            this.Consignment = new HashSet<Consignment>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string Profile { get; set; }
        public string Phone { get; set; }
        public int Capital { get; set; }
        public int NumberOfRegistration { get; set; }
        public System.DateTime DateOfRegistration { get; set; }
        public int Contribution { get; set; }
        public Nullable<int> OwnerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consignment> Consignment { get; set; }
        public virtual Owner Owner { get; set; }
    }
}
